name = "zalando-pro-app"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
NOWPAYMENTS_API_KEY = "S3ZNPCF-Q1HMRJS-NWCXK3N-B7W1PHN"
NOWPAYMENTS_IPN_SECRET = "KVxLsIowDGX6mp2agNZ7j3K0Bdy3Cr4f"
SUPABASE_URL = "https://mklzftbjvngwwiivdkhs.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "sb_publishable_vfa-EIY2FIK0WM1yaRicOQ_FmDXE51x"
